version: "3.6"

services:
  web:
    image: cartloop/web
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    depends_on:
      - db
      - celery
      - redis_db
#      - pgadmin
    build: .
    command: bash -c "ls -al && gunicorn api.wsgi -c /code/api/gunicorn_config.py"
    restart: always
    networks:
      - cartloop
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./src
        target: /code
    env_file:
      - .env
    container_name: cartloop_web

  db:
    image: cartloop/db
    restart: 'no'
    build: './postgres'
    ports:
      - "5432:5432"
    networks:
      - cartloop
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    container_name: cartloop_db

  celery:
    image: cartloop/celery
    build: .
    command: celery -A api worker -l info -B
    env_file:
      - .env
    environment:
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
    restart: always
    volumes:
      - ./src:/code
    links:
      - redis_db
    depends_on:
      - redis_db
    networks:
      - cartloop
    container_name: cartloop_celery

  redis_db:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - cartloop
    container_name: cartloop_redis

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: 'no'
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      PGADMIN_LISTEN_PORT: 80
#    ports:
#      - "2020:80"
#    volumes:
#      - ./pgadmin-data:/var/lib/pgadmin
#    depends_on:
#      - db
#    links:
#      - "db:psql-server"
#    networks:
#      - cartloop
#    container_name: cartloop_pgadmin

networks:
  cartloop:
    driver: bridge
