# Generated by Django 3.1.3 on 2020-12-04 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_store_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='clientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_convs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='operatorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator_convs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.store'),
        ),
    ]
